export enum DateEnum {
    DATEFORMAT_MMDDYYYY = 'MM/dd/yyyy',
    DATEFORMAT_DDMMYYYY = 'dd/MM/yyyy',
    DATEFORMAT_YYYYMMDD = 'yyyy/MM/dd',
    DATEFORMAT_YYYYMMMDD = 'yyyy/MMM/dd',
    DATEFORMAT_YYYYMMDDHHMMS  = 'yyyy/MM/dd h:mm:s a',
    DATEFORMAT_MMDDYYYYHHMMS = 'MM/dd/yyyy h:mm:s a',
    DATEFORMAT_DDMMYYYYHHMMS = 'dd/MM/yyyy h:mm:s a',
    DATEFORMAT_DDMMMYYYYHHMMS = 'dd/MMM/yyyy h:mm:s a',
    DATEFORMAT_MM_DD_YYYY = 'MM-dd-yyyy',
    DATEFORMAT_DD_MM_YYYY = 'dd-MM-yyyy',
    DATEFORMAT_YYYY_MM_DD = 'yyyy-MM-dd',
    DATEFORMAT_YYYY_MMM_DD = 'yyyy-MMM-dd',
    DATEFORMAT_YYYY_MM_DDHHMMS  = 'yyyy-MM-dd h:mm:s a',
    DATEFORMAT_MM_DD_YYYYHHMMS = 'MM-dd-yyyy h:mm:s a',
    DATEFORMAT_DD_MM_YYYYHHMMS = 'dd-MM-yyyy h:mm:s a',
    DATEFORMAT_DD_MMM_YYYYHHMMS = 'dd-MMM-yyyy h:mm:s a',
    LOCAL_ENUS= 'en-US',
    YEAR = 'year',
    MONTH = 'months',
    DAYS = 'days',
    DATERANGEIN_ADD = 'add',
    DATERANGEIN_SUBTRACT= 'subtract',
}
